FROM azul/zulu-openjdk-alpine:11
ARG JAR_FILE=build/libs/springboot-rabbitmq-1.0.jar
VOLUME /tmp
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]